import type { KnowledgeModule } from "../types";
export const googleAdsKnowledge: KnowledgeModule = {
  domain: "google-ads", version: "1.0.0",
  rules: [
    { id: "gads.quality_score_low", domain: "google-ads", title: "Quality Score baixo",
      description: "QS abaixo de 5 aumenta CPC e reduz impressões elegíveis.",
      when: ["quality_score < 5"],
      recommend: ["reescrever_anuncio", "ajustar_landing_page", "revisar_keywords"],
      severity: "warn", references: [], version: "1.0.0" },
    { id: "gads.search_impression_share_low", domain: "google-ads",
      title: "Search Impression Share baixo",
      description: "SIS abaixo de 30% indica orçamento ou lance limitando exposição.",
      when: ["search_impression_share < 0.3"],
      recommend: ["aumentar_orcamento", "revisar_estrategia_lance"],
      severity: "warn", references: [], version: "1.0.0" },
    { id: "gads.negative_keywords_missing", domain: "google-ads",
      title: "Lista de negativas insuficiente",
      description: "Ausência de negativas gera desperdício de investimento.",
      when: ["negative_keyword_count < 20"],
      recommend: ["construir_lista_negativas", "revisar_query_report"],
      severity: "warn", references: [], version: "1.0.0" },
    { id: "gads.conversion_tracking_missing", domain: "google-ads",
      title: "Conversion tracking ausente",
      description: "Sem conversão registrada não há otimização por resultado.",
      when: ["conversion_tracking = false"],
      recommend: ["ativar_conversion_tracking", "importar_ga4"],
      severity: "critical", references: [], version: "1.0.0" },
  ],
};
