/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AppSigmaRouteImport } from './routes/app.sigma'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppOrganizacaoRouteImport } from './routes/app.organizacao'
import { Route as AppMetaAdsRouteImport } from './routes/app.meta-ads'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppInteligenciaRouteImport } from './routes/app.inteligencia'
import { Route as AppIntegracoesRouteImport } from './routes/app.integracoes'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppGoogleAdsRouteImport } from './routes/app.google-ads'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppExecutivoRouteImport } from './routes/app.executivo'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAutomacoesRouteImport } from './routes/app.automacoes'
import { Route as AppAssinaturaRouteImport } from './routes/app.assinatura'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppWorkspaceIndexRouteImport } from './routes/app.workspace.index'
import { Route as AppWhatsappIndexRouteImport } from './routes/app.whatsapp.index'
import { Route as AppTicketsIndexRouteImport } from './routes/app.tickets.index'
import { Route as AppSigmaIndexRouteImport } from './routes/app.sigma.index'
import { Route as AppMetaAdsIndexRouteImport } from './routes/app.meta-ads.index'
import { Route as AppMarketingIndexRouteImport } from './routes/app.marketing.index'
import { Route as AppLeadsIndexRouteImport } from './routes/app.leads.index'
import { Route as AppInteligenciaIndexRouteImport } from './routes/app.inteligencia.index'
import { Route as AppIaIndexRouteImport } from './routes/app.ia.index'
import { Route as AppGoogleAdsIndexRouteImport } from './routes/app.google-ads.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/app.financeiro.index'
import { Route as AppAutomacoesIndexRouteImport } from './routes/app.automacoes.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppWorkspaceReportsRouteImport } from './routes/app.workspace.reports'
import { Route as AppWorkspaceRecommendationsRouteImport } from './routes/app.workspace.recommendations'
import { Route as AppWorkspaceMemoryRouteImport } from './routes/app.workspace.memory'
import { Route as AppWorkspaceInsightsRouteImport } from './routes/app.workspace.insights'
import { Route as AppWorkspaceDashboardRouteImport } from './routes/app.workspace.dashboard'
import { Route as AppWorkspaceActionsRouteImport } from './routes/app.workspace.actions'
import { Route as AppWhatsappChatRouteImport } from './routes/app.whatsapp.chat'
import { Route as AppSigmaLogsRouteImport } from './routes/app.sigma.logs'
import { Route as AppSigmaConsoleRouteImport } from './routes/app.sigma.console'
import { Route as AppMetaAdsTrackingRouteImport } from './routes/app.meta-ads.tracking'
import { Route as AppMetaAdsCriativosRouteImport } from './routes/app.meta-ads.criativos'
import { Route as AppMetaAdsConversionsRouteImport } from './routes/app.meta-ads.conversions'
import { Route as AppMetaAdsCampaignsRouteImport } from './routes/app.meta-ads.campaigns'
import { Route as AppMarketingConnectRouteImport } from './routes/app.marketing.connect'
import { Route as AppMarketingProviderRouteImport } from './routes/app.marketing.$provider'
import { Route as AppLeadsKanbanRouteImport } from './routes/app.leads.kanban'
import { Route as AppLeadsCobrancasRouteImport } from './routes/app.leads.cobrancas'
import { Route as AppLeadsAtribuicaoRouteImport } from './routes/app.leads.atribuicao'
import { Route as AppInteligenciaRecomendacoesRouteImport } from './routes/app.inteligencia.recomendacoes'
import { Route as AppInteligenciaPlaybooksRouteImport } from './routes/app.inteligencia.playbooks'
import { Route as AppInteligenciaEvidenciasRouteImport } from './routes/app.inteligencia.evidencias'
import { Route as AppIaQualificarRouteImport } from './routes/app.ia.qualificar'
import { Route as AppIaCopilotoRouteImport } from './routes/app.ia.copiloto'
import { Route as AppGoogleAdsTrackingRouteImport } from './routes/app.google-ads.tracking'
import { Route as AppGoogleAdsConversionsRouteImport } from './routes/app.google-ads.conversions'
import { Route as AppGoogleAdsCampaignsRouteImport } from './routes/app.google-ads.campaigns'
import { Route as AppFinanceiroTransacoesRouteImport } from './routes/app.financeiro.transacoes'
import { Route as AppFinanceiroCategoriasRouteImport } from './routes/app.financeiro.categorias'
import { Route as AppAutomacoesExecucoesRouteImport } from './routes/app.automacoes.execucoes'
import { Route as AppAdminPilotRouteImport } from './routes/app.admin.pilot'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as ApiPublicMetricsRouteImport } from './routes/api/public/metrics'
import { Route as ApiPublicLiveRouteImport } from './routes/api/public/live'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AppInteligenciaRecomendacoesIdRouteImport } from './routes/app.inteligencia.recomendacoes.$id'
import { Route as AppInteligenciaPlaybooksIdRouteImport } from './routes/app.inteligencia.playbooks.$id'
import { Route as AppInteligenciaEvidenciasIdRouteImport } from './routes/app.inteligencia.evidencias.$id'
import { Route as AppAdminPilotDailyRouteImport } from './routes/app.admin.pilot.daily'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks.stripe'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks.mercadopago'
import { Route as ApiPublicTrackWaLinkRouteImport } from './routes/api/public/track.wa-link'
import { Route as ApiPublicTrackScriptDotjsRouteImport } from './routes/api/public/track.script[.]js'
import { Route as ApiPublicTrackEventRouteImport } from './routes/api/public/track.event'
import { Route as ApiPublicWhatsappWebhookInstanceIdRouteImport } from './routes/api/public/whatsapp.webhook.$instanceId'
import { Route as ApiPublicMetaOauthCallbackRouteImport } from './routes/api/public/meta.oauth.callback'
import { Route as ApiPublicMarketingOauthCallbackRouteImport } from './routes/api/public/marketing.oauth.callback'
import { Route as ApiPublicGoogleAdsOauthCallbackRouteImport } from './routes/api/public/google-ads.oauth.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSigmaRoute = AppSigmaRouteImport.update({
  id: '/sigma',
  path: '/sigma',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizacaoRoute = AppOrganizacaoRouteImport.update({
  id: '/organizacao',
  path: '/organizacao',
  getParentRoute: () => AppRoute,
} as any)
const AppMetaAdsRoute = AppMetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppGoogleAdsRoute = AppGoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutivoRoute = AppExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWhatsappIndexRoute = AppWhatsappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppSigmaIndexRoute = AppSigmaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSigmaRoute,
} as any)
const AppMetaAdsIndexRoute = AppMetaAdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMetaAdsRoute,
} as any)
const AppMarketingIndexRoute = AppMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaIndexRoute = AppInteligenciaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInteligenciaRoute,
} as any)
const AppIaIndexRoute = AppIaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIaRoute,
} as any)
const AppGoogleAdsIndexRoute = AppGoogleAdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGoogleAdsRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppAutomacoesIndexRoute = AppAutomacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAutomacoesRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppWorkspaceReportsRoute = AppWorkspaceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceRecommendationsRoute =
  AppWorkspaceRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceMemoryRoute = AppWorkspaceMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceInsightsRoute = AppWorkspaceInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceDashboardRoute = AppWorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceActionsRoute = AppWorkspaceActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWhatsappChatRoute = AppWhatsappChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppSigmaLogsRoute = AppSigmaLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppSigmaRoute,
} as any)
const AppSigmaConsoleRoute = AppSigmaConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppSigmaRoute,
} as any)
const AppMetaAdsTrackingRoute = AppMetaAdsTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppMetaAdsRoute,
} as any)
const AppMetaAdsCriativosRoute = AppMetaAdsCriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => AppMetaAdsRoute,
} as any)
const AppMetaAdsConversionsRoute = AppMetaAdsConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => AppMetaAdsRoute,
} as any)
const AppMetaAdsCampaignsRoute = AppMetaAdsCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppMetaAdsRoute,
} as any)
const AppMarketingConnectRoute = AppMarketingConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingProviderRoute = AppMarketingProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppLeadsKanbanRoute = AppLeadsKanbanRouteImport.update({
  id: '/leads/kanban',
  path: '/leads/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsCobrancasRoute = AppLeadsCobrancasRouteImport.update({
  id: '/leads/cobrancas',
  path: '/leads/cobrancas',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsAtribuicaoRoute = AppLeadsAtribuicaoRouteImport.update({
  id: '/leads/atribuicao',
  path: '/leads/atribuicao',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRecomendacoesRoute =
  AppInteligenciaRecomendacoesRouteImport.update({
    id: '/recomendacoes',
    path: '/recomendacoes',
    getParentRoute: () => AppInteligenciaRoute,
  } as any)
const AppInteligenciaPlaybooksRoute =
  AppInteligenciaPlaybooksRouteImport.update({
    id: '/playbooks',
    path: '/playbooks',
    getParentRoute: () => AppInteligenciaRoute,
  } as any)
const AppInteligenciaEvidenciasRoute =
  AppInteligenciaEvidenciasRouteImport.update({
    id: '/evidencias',
    path: '/evidencias',
    getParentRoute: () => AppInteligenciaRoute,
  } as any)
const AppIaQualificarRoute = AppIaQualificarRouteImport.update({
  id: '/qualificar',
  path: '/qualificar',
  getParentRoute: () => AppIaRoute,
} as any)
const AppIaCopilotoRoute = AppIaCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AppIaRoute,
} as any)
const AppGoogleAdsTrackingRoute = AppGoogleAdsTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppGoogleAdsRoute,
} as any)
const AppGoogleAdsConversionsRoute = AppGoogleAdsConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => AppGoogleAdsRoute,
} as any)
const AppGoogleAdsCampaignsRoute = AppGoogleAdsCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppGoogleAdsRoute,
} as any)
const AppFinanceiroTransacoesRoute = AppFinanceiroTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCategoriasRoute = AppFinanceiroCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppAutomacoesExecucoesRoute = AppAutomacoesExecucoesRouteImport.update({
  id: '/execucoes',
  path: '/execucoes',
  getParentRoute: () => AppAutomacoesRoute,
} as any)
const AppAdminPilotRoute = AppAdminPilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveRoute = ApiPublicLiveRouteImport.update({
  id: '/api/public/live',
  path: '/api/public/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInteligenciaRecomendacoesIdRoute =
  AppInteligenciaRecomendacoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppInteligenciaRecomendacoesRoute,
  } as any)
const AppInteligenciaPlaybooksIdRoute =
  AppInteligenciaPlaybooksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppInteligenciaPlaybooksRoute,
  } as any)
const AppInteligenciaEvidenciasIdRoute =
  AppInteligenciaEvidenciasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppInteligenciaEvidenciasRoute,
  } as any)
const AppAdminPilotDailyRoute = AppAdminPilotDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AppAdminPilotRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackWaLinkRoute = ApiPublicTrackWaLinkRouteImport.update({
  id: '/api/public/track/wa-link',
  path: '/api/public/track/wa-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackScriptDotjsRoute =
  ApiPublicTrackScriptDotjsRouteImport.update({
    id: '/api/public/track/script.js',
    path: '/api/public/track/script.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackEventRoute = ApiPublicTrackEventRouteImport.update({
  id: '/api/public/track/event',
  path: '/api/public/track/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookInstanceIdRoute =
  ApiPublicWhatsappWebhookInstanceIdRouteImport.update({
    id: '/api/public/whatsapp/webhook/$instanceId',
    path: '/api/public/whatsapp/webhook/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaOauthCallbackRoute =
  ApiPublicMetaOauthCallbackRouteImport.update({
    id: '/api/public/meta/oauth/callback',
    path: '/api/public/meta/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketingOauthCallbackRoute =
  ApiPublicMarketingOauthCallbackRouteImport.update({
    id: '/api/public/marketing/oauth/callback',
    path: '/api/public/marketing/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleAdsOauthCallbackRoute =
  ApiPublicGoogleAdsOauthCallbackRouteImport.update({
    id: '/api/public/google-ads/oauth/callback',
    path: '/api/public/google-ads/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/automacoes': typeof AppAutomacoesRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/executivo': typeof AppExecutivoRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/google-ads': typeof AppGoogleAdsRouteWithChildren
  '/app/ia': typeof AppIaRouteWithChildren
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/inteligencia': typeof AppInteligenciaRouteWithChildren
  '/app/marketing': typeof AppMarketingRouteWithChildren
  '/app/meta-ads': typeof AppMetaAdsRouteWithChildren
  '/app/organizacao': typeof AppOrganizacaoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sigma': typeof AppSigmaRouteWithChildren
  '/app/tickets': typeof AppTicketsRouteWithChildren
  '/app/whatsapp': typeof AppWhatsappRouteWithChildren
  '/app/workspace': typeof AppWorkspaceRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/app/admin/pilot': typeof AppAdminPilotRouteWithChildren
  '/app/automacoes/execucoes': typeof AppAutomacoesExecucoesRoute
  '/app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/app/financeiro/transacoes': typeof AppFinanceiroTransacoesRoute
  '/app/google-ads/campaigns': typeof AppGoogleAdsCampaignsRoute
  '/app/google-ads/conversions': typeof AppGoogleAdsConversionsRoute
  '/app/google-ads/tracking': typeof AppGoogleAdsTrackingRoute
  '/app/ia/copiloto': typeof AppIaCopilotoRoute
  '/app/ia/qualificar': typeof AppIaQualificarRoute
  '/app/inteligencia/evidencias': typeof AppInteligenciaEvidenciasRouteWithChildren
  '/app/inteligencia/playbooks': typeof AppInteligenciaPlaybooksRouteWithChildren
  '/app/inteligencia/recomendacoes': typeof AppInteligenciaRecomendacoesRouteWithChildren
  '/app/leads/atribuicao': typeof AppLeadsAtribuicaoRoute
  '/app/leads/cobrancas': typeof AppLeadsCobrancasRoute
  '/app/leads/kanban': typeof AppLeadsKanbanRoute
  '/app/marketing/$provider': typeof AppMarketingProviderRoute
  '/app/marketing/connect': typeof AppMarketingConnectRoute
  '/app/meta-ads/campaigns': typeof AppMetaAdsCampaignsRoute
  '/app/meta-ads/conversions': typeof AppMetaAdsConversionsRoute
  '/app/meta-ads/criativos': typeof AppMetaAdsCriativosRoute
  '/app/meta-ads/tracking': typeof AppMetaAdsTrackingRoute
  '/app/sigma/console': typeof AppSigmaConsoleRoute
  '/app/sigma/logs': typeof AppSigmaLogsRoute
  '/app/whatsapp/chat': typeof AppWhatsappChatRoute
  '/app/workspace/actions': typeof AppWorkspaceActionsRoute
  '/app/workspace/dashboard': typeof AppWorkspaceDashboardRoute
  '/app/workspace/insights': typeof AppWorkspaceInsightsRoute
  '/app/workspace/memory': typeof AppWorkspaceMemoryRoute
  '/app/workspace/recommendations': typeof AppWorkspaceRecommendationsRoute
  '/app/workspace/reports': typeof AppWorkspaceReportsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/automacoes/': typeof AppAutomacoesIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/google-ads/': typeof AppGoogleAdsIndexRoute
  '/app/ia/': typeof AppIaIndexRoute
  '/app/inteligencia/': typeof AppInteligenciaIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/marketing/': typeof AppMarketingIndexRoute
  '/app/meta-ads/': typeof AppMetaAdsIndexRoute
  '/app/sigma/': typeof AppSigmaIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
  '/app/whatsapp/': typeof AppWhatsappIndexRoute
  '/app/workspace/': typeof AppWorkspaceIndexRoute
  '/api/public/track/event': typeof ApiPublicTrackEventRoute
  '/api/public/track/script.js': typeof ApiPublicTrackScriptDotjsRoute
  '/api/public/track/wa-link': typeof ApiPublicTrackWaLinkRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/admin/pilot/daily': typeof AppAdminPilotDailyRoute
  '/app/inteligencia/evidencias/$id': typeof AppInteligenciaEvidenciasIdRoute
  '/app/inteligencia/playbooks/$id': typeof AppInteligenciaPlaybooksIdRoute
  '/app/inteligencia/recomendacoes/$id': typeof AppInteligenciaRecomendacoesIdRoute
  '/api/public/google-ads/oauth/callback': typeof ApiPublicGoogleAdsOauthCallbackRoute
  '/api/public/marketing/oauth/callback': typeof ApiPublicMarketingOauthCallbackRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/whatsapp/webhook/$instanceId': typeof ApiPublicWhatsappWebhookInstanceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/executivo': typeof AppExecutivoRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/organizacao': typeof AppOrganizacaoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/app/admin/pilot': typeof AppAdminPilotRouteWithChildren
  '/app/automacoes/execucoes': typeof AppAutomacoesExecucoesRoute
  '/app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/app/financeiro/transacoes': typeof AppFinanceiroTransacoesRoute
  '/app/google-ads/campaigns': typeof AppGoogleAdsCampaignsRoute
  '/app/google-ads/conversions': typeof AppGoogleAdsConversionsRoute
  '/app/google-ads/tracking': typeof AppGoogleAdsTrackingRoute
  '/app/ia/copiloto': typeof AppIaCopilotoRoute
  '/app/ia/qualificar': typeof AppIaQualificarRoute
  '/app/inteligencia/evidencias': typeof AppInteligenciaEvidenciasRouteWithChildren
  '/app/inteligencia/playbooks': typeof AppInteligenciaPlaybooksRouteWithChildren
  '/app/inteligencia/recomendacoes': typeof AppInteligenciaRecomendacoesRouteWithChildren
  '/app/leads/atribuicao': typeof AppLeadsAtribuicaoRoute
  '/app/leads/cobrancas': typeof AppLeadsCobrancasRoute
  '/app/leads/kanban': typeof AppLeadsKanbanRoute
  '/app/marketing/$provider': typeof AppMarketingProviderRoute
  '/app/marketing/connect': typeof AppMarketingConnectRoute
  '/app/meta-ads/campaigns': typeof AppMetaAdsCampaignsRoute
  '/app/meta-ads/conversions': typeof AppMetaAdsConversionsRoute
  '/app/meta-ads/criativos': typeof AppMetaAdsCriativosRoute
  '/app/meta-ads/tracking': typeof AppMetaAdsTrackingRoute
  '/app/sigma/console': typeof AppSigmaConsoleRoute
  '/app/sigma/logs': typeof AppSigmaLogsRoute
  '/app/whatsapp/chat': typeof AppWhatsappChatRoute
  '/app/workspace/actions': typeof AppWorkspaceActionsRoute
  '/app/workspace/dashboard': typeof AppWorkspaceDashboardRoute
  '/app/workspace/insights': typeof AppWorkspaceInsightsRoute
  '/app/workspace/memory': typeof AppWorkspaceMemoryRoute
  '/app/workspace/recommendations': typeof AppWorkspaceRecommendationsRoute
  '/app/workspace/reports': typeof AppWorkspaceReportsRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/automacoes': typeof AppAutomacoesIndexRoute
  '/app/financeiro': typeof AppFinanceiroIndexRoute
  '/app/google-ads': typeof AppGoogleAdsIndexRoute
  '/app/ia': typeof AppIaIndexRoute
  '/app/inteligencia': typeof AppInteligenciaIndexRoute
  '/app/leads': typeof AppLeadsIndexRoute
  '/app/marketing': typeof AppMarketingIndexRoute
  '/app/meta-ads': typeof AppMetaAdsIndexRoute
  '/app/sigma': typeof AppSigmaIndexRoute
  '/app/tickets': typeof AppTicketsIndexRoute
  '/app/whatsapp': typeof AppWhatsappIndexRoute
  '/app/workspace': typeof AppWorkspaceIndexRoute
  '/api/public/track/event': typeof ApiPublicTrackEventRoute
  '/api/public/track/script.js': typeof ApiPublicTrackScriptDotjsRoute
  '/api/public/track/wa-link': typeof ApiPublicTrackWaLinkRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/admin/pilot/daily': typeof AppAdminPilotDailyRoute
  '/app/inteligencia/evidencias/$id': typeof AppInteligenciaEvidenciasIdRoute
  '/app/inteligencia/playbooks/$id': typeof AppInteligenciaPlaybooksIdRoute
  '/app/inteligencia/recomendacoes/$id': typeof AppInteligenciaRecomendacoesIdRoute
  '/api/public/google-ads/oauth/callback': typeof ApiPublicGoogleAdsOauthCallbackRoute
  '/api/public/marketing/oauth/callback': typeof ApiPublicMarketingOauthCallbackRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/whatsapp/webhook/$instanceId': typeof ApiPublicWhatsappWebhookInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/automacoes': typeof AppAutomacoesRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/executivo': typeof AppExecutivoRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/google-ads': typeof AppGoogleAdsRouteWithChildren
  '/app/ia': typeof AppIaRouteWithChildren
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/inteligencia': typeof AppInteligenciaRouteWithChildren
  '/app/marketing': typeof AppMarketingRouteWithChildren
  '/app/meta-ads': typeof AppMetaAdsRouteWithChildren
  '/app/organizacao': typeof AppOrganizacaoRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sigma': typeof AppSigmaRouteWithChildren
  '/app/tickets': typeof AppTicketsRouteWithChildren
  '/app/whatsapp': typeof AppWhatsappRouteWithChildren
  '/app/workspace': typeof AppWorkspaceRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/app/admin/pilot': typeof AppAdminPilotRouteWithChildren
  '/app/automacoes/execucoes': typeof AppAutomacoesExecucoesRoute
  '/app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/app/financeiro/transacoes': typeof AppFinanceiroTransacoesRoute
  '/app/google-ads/campaigns': typeof AppGoogleAdsCampaignsRoute
  '/app/google-ads/conversions': typeof AppGoogleAdsConversionsRoute
  '/app/google-ads/tracking': typeof AppGoogleAdsTrackingRoute
  '/app/ia/copiloto': typeof AppIaCopilotoRoute
  '/app/ia/qualificar': typeof AppIaQualificarRoute
  '/app/inteligencia/evidencias': typeof AppInteligenciaEvidenciasRouteWithChildren
  '/app/inteligencia/playbooks': typeof AppInteligenciaPlaybooksRouteWithChildren
  '/app/inteligencia/recomendacoes': typeof AppInteligenciaRecomendacoesRouteWithChildren
  '/app/leads/atribuicao': typeof AppLeadsAtribuicaoRoute
  '/app/leads/cobrancas': typeof AppLeadsCobrancasRoute
  '/app/leads/kanban': typeof AppLeadsKanbanRoute
  '/app/marketing/$provider': typeof AppMarketingProviderRoute
  '/app/marketing/connect': typeof AppMarketingConnectRoute
  '/app/meta-ads/campaigns': typeof AppMetaAdsCampaignsRoute
  '/app/meta-ads/conversions': typeof AppMetaAdsConversionsRoute
  '/app/meta-ads/criativos': typeof AppMetaAdsCriativosRoute
  '/app/meta-ads/tracking': typeof AppMetaAdsTrackingRoute
  '/app/sigma/console': typeof AppSigmaConsoleRoute
  '/app/sigma/logs': typeof AppSigmaLogsRoute
  '/app/whatsapp/chat': typeof AppWhatsappChatRoute
  '/app/workspace/actions': typeof AppWorkspaceActionsRoute
  '/app/workspace/dashboard': typeof AppWorkspaceDashboardRoute
  '/app/workspace/insights': typeof AppWorkspaceInsightsRoute
  '/app/workspace/memory': typeof AppWorkspaceMemoryRoute
  '/app/workspace/recommendations': typeof AppWorkspaceRecommendationsRoute
  '/app/workspace/reports': typeof AppWorkspaceReportsRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/automacoes/': typeof AppAutomacoesIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/google-ads/': typeof AppGoogleAdsIndexRoute
  '/app/ia/': typeof AppIaIndexRoute
  '/app/inteligencia/': typeof AppInteligenciaIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/marketing/': typeof AppMarketingIndexRoute
  '/app/meta-ads/': typeof AppMetaAdsIndexRoute
  '/app/sigma/': typeof AppSigmaIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
  '/app/whatsapp/': typeof AppWhatsappIndexRoute
  '/app/workspace/': typeof AppWorkspaceIndexRoute
  '/api/public/track/event': typeof ApiPublicTrackEventRoute
  '/api/public/track/script.js': typeof ApiPublicTrackScriptDotjsRoute
  '/api/public/track/wa-link': typeof ApiPublicTrackWaLinkRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/app/admin/pilot/daily': typeof AppAdminPilotDailyRoute
  '/app/inteligencia/evidencias/$id': typeof AppInteligenciaEvidenciasIdRoute
  '/app/inteligencia/playbooks/$id': typeof AppInteligenciaPlaybooksIdRoute
  '/app/inteligencia/recomendacoes/$id': typeof AppInteligenciaRecomendacoesIdRoute
  '/api/public/google-ads/oauth/callback': typeof ApiPublicGoogleAdsOauthCallbackRoute
  '/api/public/marketing/oauth/callback': typeof ApiPublicMarketingOauthCallbackRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/whatsapp/webhook/$instanceId': typeof ApiPublicWhatsappWebhookInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/assinatura'
    | '/app/automacoes'
    | '/app/clientes'
    | '/app/executivo'
    | '/app/financeiro'
    | '/app/google-ads'
    | '/app/ia'
    | '/app/integracoes'
    | '/app/inteligencia'
    | '/app/marketing'
    | '/app/meta-ads'
    | '/app/organizacao'
    | '/app/settings'
    | '/app/sigma'
    | '/app/tickets'
    | '/app/whatsapp'
    | '/app/workspace'
    | '/app/'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/metrics'
    | '/api/public/ready'
    | '/app/admin/pilot'
    | '/app/automacoes/execucoes'
    | '/app/financeiro/categorias'
    | '/app/financeiro/transacoes'
    | '/app/google-ads/campaigns'
    | '/app/google-ads/conversions'
    | '/app/google-ads/tracking'
    | '/app/ia/copiloto'
    | '/app/ia/qualificar'
    | '/app/inteligencia/evidencias'
    | '/app/inteligencia/playbooks'
    | '/app/inteligencia/recomendacoes'
    | '/app/leads/atribuicao'
    | '/app/leads/cobrancas'
    | '/app/leads/kanban'
    | '/app/marketing/$provider'
    | '/app/marketing/connect'
    | '/app/meta-ads/campaigns'
    | '/app/meta-ads/conversions'
    | '/app/meta-ads/criativos'
    | '/app/meta-ads/tracking'
    | '/app/sigma/console'
    | '/app/sigma/logs'
    | '/app/whatsapp/chat'
    | '/app/workspace/actions'
    | '/app/workspace/dashboard'
    | '/app/workspace/insights'
    | '/app/workspace/memory'
    | '/app/workspace/recommendations'
    | '/app/workspace/reports'
    | '/app/admin/'
    | '/app/automacoes/'
    | '/app/financeiro/'
    | '/app/google-ads/'
    | '/app/ia/'
    | '/app/inteligencia/'
    | '/app/leads/'
    | '/app/marketing/'
    | '/app/meta-ads/'
    | '/app/sigma/'
    | '/app/tickets/'
    | '/app/whatsapp/'
    | '/app/workspace/'
    | '/api/public/track/event'
    | '/api/public/track/script.js'
    | '/api/public/track/wa-link'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
    | '/app/admin/pilot/daily'
    | '/app/inteligencia/evidencias/$id'
    | '/app/inteligencia/playbooks/$id'
    | '/app/inteligencia/recomendacoes/$id'
    | '/api/public/google-ads/oauth/callback'
    | '/api/public/marketing/oauth/callback'
    | '/api/public/meta/oauth/callback'
    | '/api/public/whatsapp/webhook/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/app/assinatura'
    | '/app/clientes'
    | '/app/executivo'
    | '/app/integracoes'
    | '/app/organizacao'
    | '/app/settings'
    | '/app'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/metrics'
    | '/api/public/ready'
    | '/app/admin/pilot'
    | '/app/automacoes/execucoes'
    | '/app/financeiro/categorias'
    | '/app/financeiro/transacoes'
    | '/app/google-ads/campaigns'
    | '/app/google-ads/conversions'
    | '/app/google-ads/tracking'
    | '/app/ia/copiloto'
    | '/app/ia/qualificar'
    | '/app/inteligencia/evidencias'
    | '/app/inteligencia/playbooks'
    | '/app/inteligencia/recomendacoes'
    | '/app/leads/atribuicao'
    | '/app/leads/cobrancas'
    | '/app/leads/kanban'
    | '/app/marketing/$provider'
    | '/app/marketing/connect'
    | '/app/meta-ads/campaigns'
    | '/app/meta-ads/conversions'
    | '/app/meta-ads/criativos'
    | '/app/meta-ads/tracking'
    | '/app/sigma/console'
    | '/app/sigma/logs'
    | '/app/whatsapp/chat'
    | '/app/workspace/actions'
    | '/app/workspace/dashboard'
    | '/app/workspace/insights'
    | '/app/workspace/memory'
    | '/app/workspace/recommendations'
    | '/app/workspace/reports'
    | '/app/admin'
    | '/app/automacoes'
    | '/app/financeiro'
    | '/app/google-ads'
    | '/app/ia'
    | '/app/inteligencia'
    | '/app/leads'
    | '/app/marketing'
    | '/app/meta-ads'
    | '/app/sigma'
    | '/app/tickets'
    | '/app/whatsapp'
    | '/app/workspace'
    | '/api/public/track/event'
    | '/api/public/track/script.js'
    | '/api/public/track/wa-link'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
    | '/app/admin/pilot/daily'
    | '/app/inteligencia/evidencias/$id'
    | '/app/inteligencia/playbooks/$id'
    | '/app/inteligencia/recomendacoes/$id'
    | '/api/public/google-ads/oauth/callback'
    | '/api/public/marketing/oauth/callback'
    | '/api/public/meta/oauth/callback'
    | '/api/public/whatsapp/webhook/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/assinatura'
    | '/app/automacoes'
    | '/app/clientes'
    | '/app/executivo'
    | '/app/financeiro'
    | '/app/google-ads'
    | '/app/ia'
    | '/app/integracoes'
    | '/app/inteligencia'
    | '/app/marketing'
    | '/app/meta-ads'
    | '/app/organizacao'
    | '/app/settings'
    | '/app/sigma'
    | '/app/tickets'
    | '/app/whatsapp'
    | '/app/workspace'
    | '/app/'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/metrics'
    | '/api/public/ready'
    | '/app/admin/pilot'
    | '/app/automacoes/execucoes'
    | '/app/financeiro/categorias'
    | '/app/financeiro/transacoes'
    | '/app/google-ads/campaigns'
    | '/app/google-ads/conversions'
    | '/app/google-ads/tracking'
    | '/app/ia/copiloto'
    | '/app/ia/qualificar'
    | '/app/inteligencia/evidencias'
    | '/app/inteligencia/playbooks'
    | '/app/inteligencia/recomendacoes'
    | '/app/leads/atribuicao'
    | '/app/leads/cobrancas'
    | '/app/leads/kanban'
    | '/app/marketing/$provider'
    | '/app/marketing/connect'
    | '/app/meta-ads/campaigns'
    | '/app/meta-ads/conversions'
    | '/app/meta-ads/criativos'
    | '/app/meta-ads/tracking'
    | '/app/sigma/console'
    | '/app/sigma/logs'
    | '/app/whatsapp/chat'
    | '/app/workspace/actions'
    | '/app/workspace/dashboard'
    | '/app/workspace/insights'
    | '/app/workspace/memory'
    | '/app/workspace/recommendations'
    | '/app/workspace/reports'
    | '/app/admin/'
    | '/app/automacoes/'
    | '/app/financeiro/'
    | '/app/google-ads/'
    | '/app/ia/'
    | '/app/inteligencia/'
    | '/app/leads/'
    | '/app/marketing/'
    | '/app/meta-ads/'
    | '/app/sigma/'
    | '/app/tickets/'
    | '/app/whatsapp/'
    | '/app/workspace/'
    | '/api/public/track/event'
    | '/api/public/track/script.js'
    | '/api/public/track/wa-link'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
    | '/app/admin/pilot/daily'
    | '/app/inteligencia/evidencias/$id'
    | '/app/inteligencia/playbooks/$id'
    | '/app/inteligencia/recomendacoes/$id'
    | '/api/public/google-ads/oauth/callback'
    | '/api/public/marketing/oauth/callback'
    | '/api/public/meta/oauth/callback'
    | '/api/public/whatsapp/webhook/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLiveRoute: typeof ApiPublicLiveRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
  ApiPublicTrackEventRoute: typeof ApiPublicTrackEventRoute
  ApiPublicTrackScriptDotjsRoute: typeof ApiPublicTrackScriptDotjsRoute
  ApiPublicTrackWaLinkRoute: typeof ApiPublicTrackWaLinkRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicGoogleAdsOauthCallbackRoute: typeof ApiPublicGoogleAdsOauthCallbackRoute
  ApiPublicMarketingOauthCallbackRoute: typeof ApiPublicMarketingOauthCallbackRoute
  ApiPublicMetaOauthCallbackRoute: typeof ApiPublicMetaOauthCallbackRoute
  ApiPublicWhatsappWebhookInstanceIdRoute: typeof ApiPublicWhatsappWebhookInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sigma': {
      id: '/app/sigma'
      path: '/sigma'
      fullPath: '/app/sigma'
      preLoaderRoute: typeof AppSigmaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizacao': {
      id: '/app/organizacao'
      path: '/organizacao'
      fullPath: '/app/organizacao'
      preLoaderRoute: typeof AppOrganizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meta-ads': {
      id: '/app/meta-ads'
      path: '/meta-ads'
      fullPath: '/app/meta-ads'
      preLoaderRoute: typeof AppMetaAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inteligencia': {
      id: '/app/inteligencia'
      path: '/inteligencia'
      fullPath: '/app/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes': {
      id: '/app/integracoes'
      path: '/integracoes'
      fullPath: '/app/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/google-ads': {
      id: '/app/google-ads'
      path: '/google-ads'
      fullPath: '/app/google-ads'
      preLoaderRoute: typeof AppGoogleAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/executivo': {
      id: '/app/executivo'
      path: '/executivo'
      fullPath: '/app/executivo'
      preLoaderRoute: typeof AppExecutivoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automacoes': {
      id: '/app/automacoes'
      path: '/automacoes'
      fullPath: '/app/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/': {
      id: '/app/workspace/'
      path: '/'
      fullPath: '/app/workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/whatsapp/': {
      id: '/app/whatsapp/'
      path: '/'
      fullPath: '/app/whatsapp/'
      preLoaderRoute: typeof AppWhatsappIndexRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/app/tickets/': {
      id: '/app/tickets/'
      path: '/'
      fullPath: '/app/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/app/sigma/': {
      id: '/app/sigma/'
      path: '/'
      fullPath: '/app/sigma/'
      preLoaderRoute: typeof AppSigmaIndexRouteImport
      parentRoute: typeof AppSigmaRoute
    }
    '/app/meta-ads/': {
      id: '/app/meta-ads/'
      path: '/'
      fullPath: '/app/meta-ads/'
      preLoaderRoute: typeof AppMetaAdsIndexRouteImport
      parentRoute: typeof AppMetaAdsRoute
    }
    '/app/marketing/': {
      id: '/app/marketing/'
      path: '/'
      fullPath: '/app/marketing/'
      preLoaderRoute: typeof AppMarketingIndexRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inteligencia/': {
      id: '/app/inteligencia/'
      path: '/'
      fullPath: '/app/inteligencia/'
      preLoaderRoute: typeof AppInteligenciaIndexRouteImport
      parentRoute: typeof AppInteligenciaRoute
    }
    '/app/ia/': {
      id: '/app/ia/'
      path: '/'
      fullPath: '/app/ia/'
      preLoaderRoute: typeof AppIaIndexRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/app/google-ads/': {
      id: '/app/google-ads/'
      path: '/'
      fullPath: '/app/google-ads/'
      preLoaderRoute: typeof AppGoogleAdsIndexRouteImport
      parentRoute: typeof AppGoogleAdsRoute
    }
    '/app/financeiro/': {
      id: '/app/financeiro/'
      path: '/'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/automacoes/': {
      id: '/app/automacoes/'
      path: '/'
      fullPath: '/app/automacoes/'
      preLoaderRoute: typeof AppAutomacoesIndexRouteImport
      parentRoute: typeof AppAutomacoesRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/workspace/reports': {
      id: '/app/workspace/reports'
      path: '/reports'
      fullPath: '/app/workspace/reports'
      preLoaderRoute: typeof AppWorkspaceReportsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/workspace/recommendations': {
      id: '/app/workspace/recommendations'
      path: '/recommendations'
      fullPath: '/app/workspace/recommendations'
      preLoaderRoute: typeof AppWorkspaceRecommendationsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/workspace/memory': {
      id: '/app/workspace/memory'
      path: '/memory'
      fullPath: '/app/workspace/memory'
      preLoaderRoute: typeof AppWorkspaceMemoryRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/workspace/insights': {
      id: '/app/workspace/insights'
      path: '/insights'
      fullPath: '/app/workspace/insights'
      preLoaderRoute: typeof AppWorkspaceInsightsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/workspace/dashboard': {
      id: '/app/workspace/dashboard'
      path: '/dashboard'
      fullPath: '/app/workspace/dashboard'
      preLoaderRoute: typeof AppWorkspaceDashboardRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/workspace/actions': {
      id: '/app/workspace/actions'
      path: '/actions'
      fullPath: '/app/workspace/actions'
      preLoaderRoute: typeof AppWorkspaceActionsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/whatsapp/chat': {
      id: '/app/whatsapp/chat'
      path: '/chat'
      fullPath: '/app/whatsapp/chat'
      preLoaderRoute: typeof AppWhatsappChatRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/app/sigma/logs': {
      id: '/app/sigma/logs'
      path: '/logs'
      fullPath: '/app/sigma/logs'
      preLoaderRoute: typeof AppSigmaLogsRouteImport
      parentRoute: typeof AppSigmaRoute
    }
    '/app/sigma/console': {
      id: '/app/sigma/console'
      path: '/console'
      fullPath: '/app/sigma/console'
      preLoaderRoute: typeof AppSigmaConsoleRouteImport
      parentRoute: typeof AppSigmaRoute
    }
    '/app/meta-ads/tracking': {
      id: '/app/meta-ads/tracking'
      path: '/tracking'
      fullPath: '/app/meta-ads/tracking'
      preLoaderRoute: typeof AppMetaAdsTrackingRouteImport
      parentRoute: typeof AppMetaAdsRoute
    }
    '/app/meta-ads/criativos': {
      id: '/app/meta-ads/criativos'
      path: '/criativos'
      fullPath: '/app/meta-ads/criativos'
      preLoaderRoute: typeof AppMetaAdsCriativosRouteImport
      parentRoute: typeof AppMetaAdsRoute
    }
    '/app/meta-ads/conversions': {
      id: '/app/meta-ads/conversions'
      path: '/conversions'
      fullPath: '/app/meta-ads/conversions'
      preLoaderRoute: typeof AppMetaAdsConversionsRouteImport
      parentRoute: typeof AppMetaAdsRoute
    }
    '/app/meta-ads/campaigns': {
      id: '/app/meta-ads/campaigns'
      path: '/campaigns'
      fullPath: '/app/meta-ads/campaigns'
      preLoaderRoute: typeof AppMetaAdsCampaignsRouteImport
      parentRoute: typeof AppMetaAdsRoute
    }
    '/app/marketing/connect': {
      id: '/app/marketing/connect'
      path: '/connect'
      fullPath: '/app/marketing/connect'
      preLoaderRoute: typeof AppMarketingConnectRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/app/marketing/$provider': {
      id: '/app/marketing/$provider'
      path: '/$provider'
      fullPath: '/app/marketing/$provider'
      preLoaderRoute: typeof AppMarketingProviderRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/app/leads/kanban': {
      id: '/app/leads/kanban'
      path: '/leads/kanban'
      fullPath: '/app/leads/kanban'
      preLoaderRoute: typeof AppLeadsKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/cobrancas': {
      id: '/app/leads/cobrancas'
      path: '/leads/cobrancas'
      fullPath: '/app/leads/cobrancas'
      preLoaderRoute: typeof AppLeadsCobrancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/atribuicao': {
      id: '/app/leads/atribuicao'
      path: '/leads/atribuicao'
      fullPath: '/app/leads/atribuicao'
      preLoaderRoute: typeof AppLeadsAtribuicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inteligencia/recomendacoes': {
      id: '/app/inteligencia/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/app/inteligencia/recomendacoes'
      preLoaderRoute: typeof AppInteligenciaRecomendacoesRouteImport
      parentRoute: typeof AppInteligenciaRoute
    }
    '/app/inteligencia/playbooks': {
      id: '/app/inteligencia/playbooks'
      path: '/playbooks'
      fullPath: '/app/inteligencia/playbooks'
      preLoaderRoute: typeof AppInteligenciaPlaybooksRouteImport
      parentRoute: typeof AppInteligenciaRoute
    }
    '/app/inteligencia/evidencias': {
      id: '/app/inteligencia/evidencias'
      path: '/evidencias'
      fullPath: '/app/inteligencia/evidencias'
      preLoaderRoute: typeof AppInteligenciaEvidenciasRouteImport
      parentRoute: typeof AppInteligenciaRoute
    }
    '/app/ia/qualificar': {
      id: '/app/ia/qualificar'
      path: '/qualificar'
      fullPath: '/app/ia/qualificar'
      preLoaderRoute: typeof AppIaQualificarRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/app/ia/copiloto': {
      id: '/app/ia/copiloto'
      path: '/copiloto'
      fullPath: '/app/ia/copiloto'
      preLoaderRoute: typeof AppIaCopilotoRouteImport
      parentRoute: typeof AppIaRoute
    }
    '/app/google-ads/tracking': {
      id: '/app/google-ads/tracking'
      path: '/tracking'
      fullPath: '/app/google-ads/tracking'
      preLoaderRoute: typeof AppGoogleAdsTrackingRouteImport
      parentRoute: typeof AppGoogleAdsRoute
    }
    '/app/google-ads/conversions': {
      id: '/app/google-ads/conversions'
      path: '/conversions'
      fullPath: '/app/google-ads/conversions'
      preLoaderRoute: typeof AppGoogleAdsConversionsRouteImport
      parentRoute: typeof AppGoogleAdsRoute
    }
    '/app/google-ads/campaigns': {
      id: '/app/google-ads/campaigns'
      path: '/campaigns'
      fullPath: '/app/google-ads/campaigns'
      preLoaderRoute: typeof AppGoogleAdsCampaignsRouteImport
      parentRoute: typeof AppGoogleAdsRoute
    }
    '/app/financeiro/transacoes': {
      id: '/app/financeiro/transacoes'
      path: '/transacoes'
      fullPath: '/app/financeiro/transacoes'
      preLoaderRoute: typeof AppFinanceiroTransacoesRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/categorias': {
      id: '/app/financeiro/categorias'
      path: '/categorias'
      fullPath: '/app/financeiro/categorias'
      preLoaderRoute: typeof AppFinanceiroCategoriasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/automacoes/execucoes': {
      id: '/app/automacoes/execucoes'
      path: '/execucoes'
      fullPath: '/app/automacoes/execucoes'
      preLoaderRoute: typeof AppAutomacoesExecucoesRouteImport
      parentRoute: typeof AppAutomacoesRoute
    }
    '/app/admin/pilot': {
      id: '/app/admin/pilot'
      path: '/pilot'
      fullPath: '/app/admin/pilot'
      preLoaderRoute: typeof AppAdminPilotRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live': {
      id: '/api/public/live'
      path: '/api/public/live'
      fullPath: '/api/public/live'
      preLoaderRoute: typeof ApiPublicLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inteligencia/recomendacoes/$id': {
      id: '/app/inteligencia/recomendacoes/$id'
      path: '/$id'
      fullPath: '/app/inteligencia/recomendacoes/$id'
      preLoaderRoute: typeof AppInteligenciaRecomendacoesIdRouteImport
      parentRoute: typeof AppInteligenciaRecomendacoesRoute
    }
    '/app/inteligencia/playbooks/$id': {
      id: '/app/inteligencia/playbooks/$id'
      path: '/$id'
      fullPath: '/app/inteligencia/playbooks/$id'
      preLoaderRoute: typeof AppInteligenciaPlaybooksIdRouteImport
      parentRoute: typeof AppInteligenciaPlaybooksRoute
    }
    '/app/inteligencia/evidencias/$id': {
      id: '/app/inteligencia/evidencias/$id'
      path: '/$id'
      fullPath: '/app/inteligencia/evidencias/$id'
      preLoaderRoute: typeof AppInteligenciaEvidenciasIdRouteImport
      parentRoute: typeof AppInteligenciaEvidenciasRoute
    }
    '/app/admin/pilot/daily': {
      id: '/app/admin/pilot/daily'
      path: '/daily'
      fullPath: '/app/admin/pilot/daily'
      preLoaderRoute: typeof AppAdminPilotDailyRouteImport
      parentRoute: typeof AppAdminPilotRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/wa-link': {
      id: '/api/public/track/wa-link'
      path: '/api/public/track/wa-link'
      fullPath: '/api/public/track/wa-link'
      preLoaderRoute: typeof ApiPublicTrackWaLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/script.js': {
      id: '/api/public/track/script.js'
      path: '/api/public/track/script.js'
      fullPath: '/api/public/track/script.js'
      preLoaderRoute: typeof ApiPublicTrackScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/event': {
      id: '/api/public/track/event'
      path: '/api/public/track/event'
      fullPath: '/api/public/track/event'
      preLoaderRoute: typeof ApiPublicTrackEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook/$instanceId': {
      id: '/api/public/whatsapp/webhook/$instanceId'
      path: '/api/public/whatsapp/webhook/$instanceId'
      fullPath: '/api/public/whatsapp/webhook/$instanceId'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/oauth/callback': {
      id: '/api/public/meta/oauth/callback'
      path: '/api/public/meta/oauth/callback'
      fullPath: '/api/public/meta/oauth/callback'
      preLoaderRoute: typeof ApiPublicMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketing/oauth/callback': {
      id: '/api/public/marketing/oauth/callback'
      path: '/api/public/marketing/oauth/callback'
      fullPath: '/api/public/marketing/oauth/callback'
      preLoaderRoute: typeof ApiPublicMarketingOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-ads/oauth/callback': {
      id: '/api/public/google-ads/oauth/callback'
      path: '/api/public/google-ads/oauth/callback'
      fullPath: '/api/public/google-ads/oauth/callback'
      preLoaderRoute: typeof ApiPublicGoogleAdsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminPilotRouteChildren {
  AppAdminPilotDailyRoute: typeof AppAdminPilotDailyRoute
}

const AppAdminPilotRouteChildren: AppAdminPilotRouteChildren = {
  AppAdminPilotDailyRoute: AppAdminPilotDailyRoute,
}

const AppAdminPilotRouteWithChildren = AppAdminPilotRoute._addFileChildren(
  AppAdminPilotRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminPilotRoute: typeof AppAdminPilotRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminPilotRoute: AppAdminPilotRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAutomacoesRouteChildren {
  AppAutomacoesExecucoesRoute: typeof AppAutomacoesExecucoesRoute
  AppAutomacoesIndexRoute: typeof AppAutomacoesIndexRoute
}

const AppAutomacoesRouteChildren: AppAutomacoesRouteChildren = {
  AppAutomacoesExecucoesRoute: AppAutomacoesExecucoesRoute,
  AppAutomacoesIndexRoute: AppAutomacoesIndexRoute,
}

const AppAutomacoesRouteWithChildren = AppAutomacoesRoute._addFileChildren(
  AppAutomacoesRouteChildren,
)

interface AppFinanceiroRouteChildren {
  AppFinanceiroCategoriasRoute: typeof AppFinanceiroCategoriasRoute
  AppFinanceiroTransacoesRoute: typeof AppFinanceiroTransacoesRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCategoriasRoute: AppFinanceiroCategoriasRoute,
  AppFinanceiroTransacoesRoute: AppFinanceiroTransacoesRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppGoogleAdsRouteChildren {
  AppGoogleAdsCampaignsRoute: typeof AppGoogleAdsCampaignsRoute
  AppGoogleAdsConversionsRoute: typeof AppGoogleAdsConversionsRoute
  AppGoogleAdsTrackingRoute: typeof AppGoogleAdsTrackingRoute
  AppGoogleAdsIndexRoute: typeof AppGoogleAdsIndexRoute
}

const AppGoogleAdsRouteChildren: AppGoogleAdsRouteChildren = {
  AppGoogleAdsCampaignsRoute: AppGoogleAdsCampaignsRoute,
  AppGoogleAdsConversionsRoute: AppGoogleAdsConversionsRoute,
  AppGoogleAdsTrackingRoute: AppGoogleAdsTrackingRoute,
  AppGoogleAdsIndexRoute: AppGoogleAdsIndexRoute,
}

const AppGoogleAdsRouteWithChildren = AppGoogleAdsRoute._addFileChildren(
  AppGoogleAdsRouteChildren,
)

interface AppIaRouteChildren {
  AppIaCopilotoRoute: typeof AppIaCopilotoRoute
  AppIaQualificarRoute: typeof AppIaQualificarRoute
  AppIaIndexRoute: typeof AppIaIndexRoute
}

const AppIaRouteChildren: AppIaRouteChildren = {
  AppIaCopilotoRoute: AppIaCopilotoRoute,
  AppIaQualificarRoute: AppIaQualificarRoute,
  AppIaIndexRoute: AppIaIndexRoute,
}

const AppIaRouteWithChildren = AppIaRoute._addFileChildren(AppIaRouteChildren)

interface AppInteligenciaEvidenciasRouteChildren {
  AppInteligenciaEvidenciasIdRoute: typeof AppInteligenciaEvidenciasIdRoute
}

const AppInteligenciaEvidenciasRouteChildren: AppInteligenciaEvidenciasRouteChildren =
  {
    AppInteligenciaEvidenciasIdRoute: AppInteligenciaEvidenciasIdRoute,
  }

const AppInteligenciaEvidenciasRouteWithChildren =
  AppInteligenciaEvidenciasRoute._addFileChildren(
    AppInteligenciaEvidenciasRouteChildren,
  )

interface AppInteligenciaPlaybooksRouteChildren {
  AppInteligenciaPlaybooksIdRoute: typeof AppInteligenciaPlaybooksIdRoute
}

const AppInteligenciaPlaybooksRouteChildren: AppInteligenciaPlaybooksRouteChildren =
  {
    AppInteligenciaPlaybooksIdRoute: AppInteligenciaPlaybooksIdRoute,
  }

const AppInteligenciaPlaybooksRouteWithChildren =
  AppInteligenciaPlaybooksRoute._addFileChildren(
    AppInteligenciaPlaybooksRouteChildren,
  )

interface AppInteligenciaRecomendacoesRouteChildren {
  AppInteligenciaRecomendacoesIdRoute: typeof AppInteligenciaRecomendacoesIdRoute
}

const AppInteligenciaRecomendacoesRouteChildren: AppInteligenciaRecomendacoesRouteChildren =
  {
    AppInteligenciaRecomendacoesIdRoute: AppInteligenciaRecomendacoesIdRoute,
  }

const AppInteligenciaRecomendacoesRouteWithChildren =
  AppInteligenciaRecomendacoesRoute._addFileChildren(
    AppInteligenciaRecomendacoesRouteChildren,
  )

interface AppInteligenciaRouteChildren {
  AppInteligenciaEvidenciasRoute: typeof AppInteligenciaEvidenciasRouteWithChildren
  AppInteligenciaPlaybooksRoute: typeof AppInteligenciaPlaybooksRouteWithChildren
  AppInteligenciaRecomendacoesRoute: typeof AppInteligenciaRecomendacoesRouteWithChildren
  AppInteligenciaIndexRoute: typeof AppInteligenciaIndexRoute
}

const AppInteligenciaRouteChildren: AppInteligenciaRouteChildren = {
  AppInteligenciaEvidenciasRoute: AppInteligenciaEvidenciasRouteWithChildren,
  AppInteligenciaPlaybooksRoute: AppInteligenciaPlaybooksRouteWithChildren,
  AppInteligenciaRecomendacoesRoute:
    AppInteligenciaRecomendacoesRouteWithChildren,
  AppInteligenciaIndexRoute: AppInteligenciaIndexRoute,
}

const AppInteligenciaRouteWithChildren = AppInteligenciaRoute._addFileChildren(
  AppInteligenciaRouteChildren,
)

interface AppMarketingRouteChildren {
  AppMarketingProviderRoute: typeof AppMarketingProviderRoute
  AppMarketingConnectRoute: typeof AppMarketingConnectRoute
  AppMarketingIndexRoute: typeof AppMarketingIndexRoute
}

const AppMarketingRouteChildren: AppMarketingRouteChildren = {
  AppMarketingProviderRoute: AppMarketingProviderRoute,
  AppMarketingConnectRoute: AppMarketingConnectRoute,
  AppMarketingIndexRoute: AppMarketingIndexRoute,
}

const AppMarketingRouteWithChildren = AppMarketingRoute._addFileChildren(
  AppMarketingRouteChildren,
)

interface AppMetaAdsRouteChildren {
  AppMetaAdsCampaignsRoute: typeof AppMetaAdsCampaignsRoute
  AppMetaAdsConversionsRoute: typeof AppMetaAdsConversionsRoute
  AppMetaAdsCriativosRoute: typeof AppMetaAdsCriativosRoute
  AppMetaAdsTrackingRoute: typeof AppMetaAdsTrackingRoute
  AppMetaAdsIndexRoute: typeof AppMetaAdsIndexRoute
}

const AppMetaAdsRouteChildren: AppMetaAdsRouteChildren = {
  AppMetaAdsCampaignsRoute: AppMetaAdsCampaignsRoute,
  AppMetaAdsConversionsRoute: AppMetaAdsConversionsRoute,
  AppMetaAdsCriativosRoute: AppMetaAdsCriativosRoute,
  AppMetaAdsTrackingRoute: AppMetaAdsTrackingRoute,
  AppMetaAdsIndexRoute: AppMetaAdsIndexRoute,
}

const AppMetaAdsRouteWithChildren = AppMetaAdsRoute._addFileChildren(
  AppMetaAdsRouteChildren,
)

interface AppSigmaRouteChildren {
  AppSigmaConsoleRoute: typeof AppSigmaConsoleRoute
  AppSigmaLogsRoute: typeof AppSigmaLogsRoute
  AppSigmaIndexRoute: typeof AppSigmaIndexRoute
}

const AppSigmaRouteChildren: AppSigmaRouteChildren = {
  AppSigmaConsoleRoute: AppSigmaConsoleRoute,
  AppSigmaLogsRoute: AppSigmaLogsRoute,
  AppSigmaIndexRoute: AppSigmaIndexRoute,
}

const AppSigmaRouteWithChildren = AppSigmaRoute._addFileChildren(
  AppSigmaRouteChildren,
)

interface AppTicketsRouteChildren {
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppWhatsappRouteChildren {
  AppWhatsappChatRoute: typeof AppWhatsappChatRoute
  AppWhatsappIndexRoute: typeof AppWhatsappIndexRoute
}

const AppWhatsappRouteChildren: AppWhatsappRouteChildren = {
  AppWhatsappChatRoute: AppWhatsappChatRoute,
  AppWhatsappIndexRoute: AppWhatsappIndexRoute,
}

const AppWhatsappRouteWithChildren = AppWhatsappRoute._addFileChildren(
  AppWhatsappRouteChildren,
)

interface AppWorkspaceRouteChildren {
  AppWorkspaceActionsRoute: typeof AppWorkspaceActionsRoute
  AppWorkspaceDashboardRoute: typeof AppWorkspaceDashboardRoute
  AppWorkspaceInsightsRoute: typeof AppWorkspaceInsightsRoute
  AppWorkspaceMemoryRoute: typeof AppWorkspaceMemoryRoute
  AppWorkspaceRecommendationsRoute: typeof AppWorkspaceRecommendationsRoute
  AppWorkspaceReportsRoute: typeof AppWorkspaceReportsRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceActionsRoute: AppWorkspaceActionsRoute,
  AppWorkspaceDashboardRoute: AppWorkspaceDashboardRoute,
  AppWorkspaceInsightsRoute: AppWorkspaceInsightsRoute,
  AppWorkspaceMemoryRoute: AppWorkspaceMemoryRoute,
  AppWorkspaceRecommendationsRoute: AppWorkspaceRecommendationsRoute,
  AppWorkspaceReportsRoute: AppWorkspaceReportsRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppAutomacoesRoute: typeof AppAutomacoesRouteWithChildren
  AppClientesRoute: typeof AppClientesRoute
  AppExecutivoRoute: typeof AppExecutivoRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppGoogleAdsRoute: typeof AppGoogleAdsRouteWithChildren
  AppIaRoute: typeof AppIaRouteWithChildren
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppInteligenciaRoute: typeof AppInteligenciaRouteWithChildren
  AppMarketingRoute: typeof AppMarketingRouteWithChildren
  AppMetaAdsRoute: typeof AppMetaAdsRouteWithChildren
  AppOrganizacaoRoute: typeof AppOrganizacaoRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSigmaRoute: typeof AppSigmaRouteWithChildren
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppWhatsappRoute: typeof AppWhatsappRouteWithChildren
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLeadsAtribuicaoRoute: typeof AppLeadsAtribuicaoRoute
  AppLeadsCobrancasRoute: typeof AppLeadsCobrancasRoute
  AppLeadsKanbanRoute: typeof AppLeadsKanbanRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppAutomacoesRoute: AppAutomacoesRouteWithChildren,
  AppClientesRoute: AppClientesRoute,
  AppExecutivoRoute: AppExecutivoRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppGoogleAdsRoute: AppGoogleAdsRouteWithChildren,
  AppIaRoute: AppIaRouteWithChildren,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppInteligenciaRoute: AppInteligenciaRouteWithChildren,
  AppMarketingRoute: AppMarketingRouteWithChildren,
  AppMetaAdsRoute: AppMetaAdsRouteWithChildren,
  AppOrganizacaoRoute: AppOrganizacaoRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSigmaRoute: AppSigmaRouteWithChildren,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppWhatsappRoute: AppWhatsappRouteWithChildren,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLeadsAtribuicaoRoute: AppLeadsAtribuicaoRoute,
  AppLeadsCobrancasRoute: AppLeadsCobrancasRoute,
  AppLeadsKanbanRoute: AppLeadsKanbanRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLiveRoute: ApiPublicLiveRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
  ApiPublicTrackEventRoute: ApiPublicTrackEventRoute,
  ApiPublicTrackScriptDotjsRoute: ApiPublicTrackScriptDotjsRoute,
  ApiPublicTrackWaLinkRoute: ApiPublicTrackWaLinkRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicGoogleAdsOauthCallbackRoute: ApiPublicGoogleAdsOauthCallbackRoute,
  ApiPublicMarketingOauthCallbackRoute: ApiPublicMarketingOauthCallbackRoute,
  ApiPublicMetaOauthCallbackRoute: ApiPublicMetaOauthCallbackRoute,
  ApiPublicWhatsappWebhookInstanceIdRoute:
    ApiPublicWhatsappWebhookInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
