/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWhatsappIndexRouteImport } from './routes/app.whatsapp.index'
import { Route as AppLeadsIndexRouteImport } from './routes/app.leads.index'
import { Route as AppWhatsappChatRouteImport } from './routes/app.whatsapp.chat'
import { Route as AppLeadsKanbanRouteImport } from './routes/app.leads.kanban'
import { Route as ApiPublicWhatsappWebhookInstanceIdRouteImport } from './routes/api/public/whatsapp.webhook.$instanceId'
import { Route as ApiPublicMetaOauthCallbackRouteImport } from './routes/api/public/meta.oauth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappIndexRoute = AppWhatsappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappChatRoute = AppWhatsappChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppLeadsKanbanRoute = AppLeadsKanbanRouteImport.update({
  id: '/leads/kanban',
  path: '/leads/kanban',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWhatsappWebhookInstanceIdRoute =
  ApiPublicWhatsappWebhookInstanceIdRouteImport.update({
    id: '/api/public/whatsapp/webhook/$instanceId',
    path: '/api/public/whatsapp/webhook/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaOauthCallbackRoute =
  ApiPublicMetaOauthCallbackRouteImport.update({
    id: '/api/public/meta/oauth/callback',
    path: '/api/public/meta/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/leads/kanban': typeof AppLeadsKanbanRoute
  '/app/whatsapp/chat': typeof AppWhatsappChatRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/whatsapp/': typeof AppWhatsappIndexRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/whatsapp/webhook/$instanceId': typeof ApiPublicWhatsappWebhookInstanceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/leads/kanban': typeof AppLeadsKanbanRoute
  '/app/whatsapp/chat': typeof AppWhatsappChatRoute
  '/app/leads': typeof AppLeadsIndexRoute
  '/app/whatsapp': typeof AppWhatsappIndexRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/whatsapp/webhook/$instanceId': typeof ApiPublicWhatsappWebhookInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/leads/kanban': typeof AppLeadsKanbanRoute
  '/app/whatsapp/chat': typeof AppWhatsappChatRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/whatsapp/': typeof AppWhatsappIndexRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/whatsapp/webhook/$instanceId': typeof ApiPublicWhatsappWebhookInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/'
    | '/app/leads/kanban'
    | '/app/whatsapp/chat'
    | '/app/leads/'
    | '/app/whatsapp/'
    | '/api/public/meta/oauth/callback'
    | '/api/public/whatsapp/webhook/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/settings'
    | '/app'
    | '/app/leads/kanban'
    | '/app/whatsapp/chat'
    | '/app/leads'
    | '/app/whatsapp'
    | '/api/public/meta/oauth/callback'
    | '/api/public/whatsapp/webhook/$instanceId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/settings'
    | '/app/whatsapp'
    | '/app/'
    | '/app/leads/kanban'
    | '/app/whatsapp/chat'
    | '/app/leads/'
    | '/app/whatsapp/'
    | '/api/public/meta/oauth/callback'
    | '/api/public/whatsapp/webhook/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicMetaOauthCallbackRoute: typeof ApiPublicMetaOauthCallbackRoute
  ApiPublicWhatsappWebhookInstanceIdRoute: typeof ApiPublicWhatsappWebhookInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp/': {
      id: '/app/whatsapp/'
      path: '/'
      fullPath: '/app/whatsapp/'
      preLoaderRoute: typeof AppWhatsappIndexRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp/chat': {
      id: '/app/whatsapp/chat'
      path: '/chat'
      fullPath: '/app/whatsapp/chat'
      preLoaderRoute: typeof AppWhatsappChatRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/app/leads/kanban': {
      id: '/app/leads/kanban'
      path: '/leads/kanban'
      fullPath: '/app/leads/kanban'
      preLoaderRoute: typeof AppLeadsKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/whatsapp/webhook/$instanceId': {
      id: '/api/public/whatsapp/webhook/$instanceId'
      path: '/api/public/whatsapp/webhook/$instanceId'
      fullPath: '/api/public/whatsapp/webhook/$instanceId'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/oauth/callback': {
      id: '/api/public/meta/oauth/callback'
      path: '/api/public/meta/oauth/callback'
      fullPath: '/api/public/meta/oauth/callback'
      preLoaderRoute: typeof ApiPublicMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppWhatsappRouteChildren {
  AppWhatsappChatRoute: typeof AppWhatsappChatRoute
  AppWhatsappIndexRoute: typeof AppWhatsappIndexRoute
}

const AppWhatsappRouteChildren: AppWhatsappRouteChildren = {
  AppWhatsappChatRoute: AppWhatsappChatRoute,
  AppWhatsappIndexRoute: AppWhatsappIndexRoute,
}

const AppWhatsappRouteWithChildren = AppWhatsappRoute._addFileChildren(
  AppWhatsappRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppWhatsappRoute: typeof AppWhatsappRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLeadsKanbanRoute: typeof AppLeadsKanbanRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppWhatsappRoute: AppWhatsappRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLeadsKanbanRoute: AppLeadsKanbanRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicMetaOauthCallbackRoute: ApiPublicMetaOauthCallbackRoute,
  ApiPublicWhatsappWebhookInstanceIdRoute:
    ApiPublicWhatsappWebhookInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
